edu/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('about', views.about, name='about'),
    path('facts', views.facts, name='facts'),
    path('resources', views.resources, name='resources'),
    path('resources/<int:id>', views.resources, name='specific_resource'),
    path('contact', views.contact, name='contact'),
    path('community', views.community, name='community'),
    path('login', views.loginPageView, name='login'),
    path('register', views.registerPageView, name='register'),
]

prescribeless/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('edu.urls')),
    path('portal/', include('prescriber_portal.urls')),
]

prescriber_portal/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.indexPageView, name='prescriber_index'),
    path('search/', views.searchPageView, name='search'),
    path('search/<entity>/', views.searchPageView, name='search_entity'),
    path('details/<entity>/<int:id>/', views.detailsPageView, name='details'),
    path('recommend/<entity>/', views.recommendPageView, name='recommend'),
    path('predtotpresc/', views.PredTotPrescPageView, name='predtotpresc'),
    path('predprescop/', views.PredPrescOp, name='predprescop'),
    path('showprescribers/', views.showPrescribersPageView, name="showprescribers"),
    path("deleteprescriber/<int:npi>/", views.deletePrescriberPageView, name="deletePrescriber"),
    path("addprescriber/", views.addPrescriberPageView, name="addPrescriber"),
    path('updateprescriber/<int:npi>/', views.updatePrescriberPageView, name="updateprescriber"),
] 

prescriber_portal/models.py
from django.db import models

class PdDrug(models.Model):
    drugid = models.AutoField(primary_key=True, db_column='drugid')
    drugname = models.CharField(max_length=30)
    isopioid = models.BooleanField()

    class Meta:
        db_table = 'pd_drug'

    def __str__(self):
        return self.drugname


class PdStatedata(models.Model):
    state = models.CharField(max_length=14, db_column='state')
    stateabbrev = models.CharField(primary_key=True, max_length=2)
    population = models.IntegerField()
    deaths = models.IntegerField()

    class Meta:
        db_table = 'pd_statedata'

    def __str__(self):
        return self.state
    


class PdPrescriber(models.Model):
    npi = models.BigIntegerField(primary_key=True)
    fname = models.CharField(max_length=20)
    lname = models.CharField(max_length=20)
    gender = models.CharField(max_length=1)
    state = models.ForeignKey(PdStatedata, on_delete=models.DO_NOTHING, db_column='state')
    specialty = models.CharField(max_length=200)
    isopioidprescriber = models.BooleanField()
    totalprescriptions = models.IntegerField()

    class Meta:
        db_table = 'pd_prescriber'
        
    def __str__(self):
        return self.fname + ' ' + self.lname

class PdCredential(models.Model):
    npi = models.BigIntegerField(primary_key=True)
    credential = models.CharField(max_length=20)

    class Meta:
        db_table = 'pd_credential'
        unique_together = (('npi', 'credential'),)

class PdPrescriptionquantity(models.Model):
    npi = models.BigIntegerField(primary_key=True)
    drugid = models.ForeignKey(PdDrug, on_delete=models.DO_NOTHING, db_column="drugid")
    quantity = models.IntegerField()

    class Meta:
        db_table = 'pd_prescriptionquantity'
        unique_together = (('npi', 'drugid'),)
        managed = False


class PdTriple(models.Model):
    id = models.AutoField(primary_key=True)
    prescriberid = models.BigIntegerField()
    drugname = models.CharField(max_length=30)
    qty = models.IntegerField()

    class Meta:
        db_table = 'pd_triple'
        managed = False

prescriber_portal/forms.py
from django import forms
from .models import PdDrug, PdPrescriber
from django.forms import ModelForm


STATES = (
    ('', 'Select State'),
    ('AL', 'Alabama'),
    ('AK', 'Alaska'),
    ('AZ', 'Arizona'),
    ('AR', 'Arkansas'),
    ('CA', 'California'),
    ('CO', 'Colorado'),
    ('CT', 'Connecticut'),
    ('DE', 'Delaware'),
    ('FL', 'Florida'),
    ('GA', 'Georgia'),
    ('HI', 'Hawaii'),
    ('ID', 'Idaho'),
    ('IL', 'Illinois'),
    ('IN', 'Indiana'),
    ('IA', 'Iowa'),
    ('KS', 'Kansas'),
    ('KY', 'Kentucky'),
    ('LA', 'Louisiana'),
    ('ME', 'Maine'),
    ('MD', 'Maryland'),
    ('MA', 'Massachusetts'),
    ('MI', 'Michigan'),
    ('MN', 'Minnesota'),
    ('MS', 'Mississippi'),
    ('MO', 'Missouri'),
    ('MT', 'Montana'),
    ('NE', 'Nebraska'),
    ('NV', 'Nevada'),
    ('NH', 'New Hampshire'),
    ('NJ', 'New Jersey'),
    ('NM', 'New Mexico'),
    ('NY', 'New York'),
    ('NC', 'North Carolina'),
    ('ND', 'North Dakota'),
    ('OH', 'Ohio'),
    ('OK', 'Oklahoma'),
    ('OR', 'Oregon'),
    ('PA', 'Pennsylvania'),
    ('RI', 'Rhode Island'),
    ('SC', 'South Carolina'),
    ('SD', 'South Dakota'),
    ('TN', 'Tennessee'),
    ('TX', 'Texas'),
    ('UT', 'Utah'),
    ('VT', 'Vermont'),
    ('VA', 'Virginia'),
    ('WA', 'Washington'),
    ('WV', 'West Virginia'),
    ('WI', 'Wisconsin'),
    ('WY', 'Wyoming'),
)

CREDENTIALS = (
('','Select Credential'),
('ACNP','A.C.N.P.'),
('ACNPBC','A.C.N.P.-B.C.'),
('AGACNP','A.G.A.C.N.P.'),
('ANP','A.N.P.'),
('ANPBC','A.N.P.-B.C.'),
('ANPC','A.N.P.-C.'),
('APN','A.P.N.'),
('APNC','A.P.N.-C.'),
('APNP','A.P.N.P.'),
('APRN','A.P.R.N.'),
('APRNBC','A.P.R.N.-B.C.'),
('ARNP','A.R.N.P.'),
('ARNPBC','A.R.N.P.-B.C.'),
('ARNPC','A.R.N.P.-C.'),
('BS','B.S.'),
('BSN','B.S.N.'),
('CANP','C.A.N.P.'),
('CCNS','C.C.N.S.'),
('CCRN','C.C.R.N.'),
('CFNP','C.F.N.P.'),
('CNM','C.N.M.'),
('CNNP','C.N.N.P.'),
('CNP','C.N.P.'),
('CNS','C.N.S.'),
('CRN','C.R.N.'),
('CRNA','C.R.N.A.'),
('CRNP','C.R.N.P.'),
('CS','C.S.'),
('DCNP','D.C.N.P.'),
('DDS','D.D.S.'),
('DMD','D.M.D.'),
('DNP','D.N.P.'),
('DPM','D.P.M.'),
('FAAFP','F.A.A.F.P.'),
('FACA','F.A.C.A.'),
('FACC','F.A.C.C.'),
('FACE','F.A.C.E.'),
('FACG','F.A.C.G.'),
('FACP','F.A.C.P.'),
('FACS','F.A.C.S.'),
('FCCP','F.C.C.P.'),
('FNP','F.N.P.'),
('FNPBC','F.N.P.-B.C.'),
('FNPC','F.N.P.-C.'),
('FPMHNP','F.P.M.H.N.P.'),
('FSCAI','F.S.C.A.I.'),
('FSVM','F.S.V.M.'),
('GNP','G.N.P.'),
('GNPBC','G.N.P.-B.C.'),
('LACC','L.A.C.C.'),
('LP','L.P.'),
('MA','M.A.'),
('MB','M.B.'),
('MBA','M.B.A.'),
('MBBCH','M.B.B.C.H.'),
('MBBS','M.B.B.S.'),
('MD','M.D.'),
('MHS','M.H.S.'),
('MMS','M.M.S.'),
('MPAS','M.P.A.S.'),
('MPH','M.P.H.'),
('MRCP','M.R.C.P.'),
('MS','M.S.'),
('MSHS','M.S.H.S.'),
('MSN','M.S.N.'),
('NASPE','N.A.S.P.E.'),
('ND','N.D.'),
('NP','N.P.'),
('NPP','N.P.P.'),
('OD','O.D.'),
('PA','P.A.'),
('PAC','P.A.C.'),
('PC','P.C.'),
('PharmD','Pharm.D.'),
('PhD','Ph.D.'),
('PMHNP','P.M.H.N.P.'),
('PMHNPBC','P.M.H.N.P.-B.C.'),
('PMHNPC','P.M.H.N.P.-C.'),
('PSYNP','P.S.Y.N.P.'),
('PT','P.T.'),
('RN','R.N.'),
('RNCS','R.N.C.S.'),
('RPAC','R.P.A.C.'),
('RPH','R.P.H.'),
('VMD','V.M.D.'),
('WHNP','W.H.N.P.'),
)

SPECIALITY = (
('','Select Speciality'),
('Allergy/Immunology','Allergy/Immunology'),
('Anesthesiology','Anesthesiology'),
('Cardiac Electrophysiology','Cardiac Electrophysiology'),
('Cardiac Surgery','Cardiac Surgery'),
('Cardiology','Cardiology'),
('Certified Clinical Nurse Specialist','Certified Clinical Nurse Specialist'),
('Certified Nurse Midwife','Certified Nurse Midwife'),
('Clinic/Center','Clinic/Center'),
('Colorectal Surgery (formerly proctology)','Colorectal Surgery (formerly proctology)'),
('Community Health Worker','Community Health Worker'),
('Critical Care (Intensivists)','Critical Care (Intensivists)'),
('CRNA','CRNA'),
('Dentist','Dentist'),
('Dermatology','Dermatology'),
('Diagnostic Radiology','Diagnostic Radiology'),
('Emergency Medicine','Emergency Medicine'),
('Endocrinology','Endocrinology'),
('Family Medicine','Family Medicine'),
('Family Practice','Family Practice'),
('Gastroenterology','Gastroenterology'),
('General Acute Care Hospital','General Acute Care Hospital'),
('General Practice','General Practice'),
('General Surgery','General Surgery'),
('Geriatric Medicine','Geriatric Medicine'),
('Geriatric Psychiatry','Geriatric Psychiatry'),
('Gynecological/Oncology','Gynecological/Oncology'),
('Health Maintenance Organization','Health Maintenance Organization'),
('Hematology','Hematology'),
('Hematology/Oncology','Hematology/Oncology'),
('Hospice and Palliative Care','Hospice and Palliative Care'),
('Hospitalist','Hospitalist'),
('Infectious Disease','Infectious Disease'),
('Internal Medicine','Internal Medicine'),
('Interventional Pain Management','Interventional Pain Management'),
('Interventional Radiology','Interventional Radiology'),
('Legal Medicine','Legal Medicine'),
('Maxillofacial Surgery','Maxillofacial Surgery'),
('Medical Oncology','Medical Oncology'),
('Multispecialty Clinic/Group Practice','Multispecialty Clinic/Group Practice'),
('Nephrology','Nephrology'),
('Neurology','Neurology'),
('Neuropsychiatry','Neuropsychiatry'),
('Neurosurgery','Neurosurgery'),
('Nuclear Medicine','Nuclear Medicine'),
('Nurse Practitioner','Nurse Practitioner'),
('Obstetrics/Gynecology','Obstetrics/Gynecology'),
('Ophthalmology','Ophthalmology'),
('Optometry','Optometry'),
('Oral Surgery (dentists only)','Oral Surgery (dentists only)'),
('Orthopedic Surgery','Orthopedic Surgery'),
('Osteopathic Manipulative Medicine','Osteopathic Manipulative Medicine'),
('Otolaryngology','Otolaryngology'),
('Pain Management','Pain Management'),
('Pediatric Medicine','Pediatric Medicine'),
('Pharmacist','Pharmacist'),
('Physical Medicine and Rehabilitation','Physical Medicine and Rehabilitation'),
('Physician Assistant','Physician Assistant'),
('Plastic and Reconstructive Surgery','Plastic and Reconstructive Surgery'),
('Podiatry','Podiatry'),
('Preventive Medicine','Preventive Medicine'),
('Psychiatry','Psychiatry'),
('Psychiatry & Neurology','Psychiatry & Neurology'),
('Psychologist (billing independently)','Psychologist (billing independently)'),
('Pulmonary Disease','Pulmonary Disease'),
('Radiation Oncology','Radiation Oncology'),
('Registered Nurse','Registered Nurse'),
('Rheumatology','Rheumatology'),
('Specialist','Specialist'),
('Sports Medicine','Sports Medicine'),
('Student in an Organized Health Care Education/Training Program','Student in an Organized Health Care Education/Training Program'),
('Surgical Oncology','Surgical Oncology'),
('Thoracic Surgery','Thoracic Surgery'),
('Unknown Physician Specialty Code','Unknown Physician Specialty Code'),
('Urology','Urology'),
('Vascular Surgery','Vascular Surgery')
)

GENDERS = (('U', 'Unspecified') , ('F', 'Female') , ('M', 'Male'))

RESULT_SET_CHOICES = (
(10, 10),
(25, 25),
(50, 50),
(100, 100),
('ALL', 'All'),
)

PRESCRIBER_SORT_CHOICES = (
    ('', 'Select'), ('F_NAME', 'First Name A-Z'), ('~F_NAME', 'First Name Z-A'), ('L_NAME', 'Last Name A-Z'), ('~L_NAME', 'Last Name Z-A'), ('TOTAL_PRESCRIPTIONS', 'Total Prescriptions (Low - High)'), ('~TOTAL_PRESCRIPTIONS', 'Total Prescriptions (High - Low)')
    )

DRUG_SORT_CHOICES = (
    ('', 'Select'), ('DRUG_NAME', 'Drug Name A-Z'), ('~DRUG_NAME', 'Drug Name Z-A'),
)
class DrugForm(forms.Form):
    drugname = forms.CharField(label='Drug Name', max_length=100, required=False)
    isopioid = forms.NullBooleanField(label='Is this an Opioid?', required=False)
    result_size = forms.ChoiceField(label='Result rows', choices=RESULT_SET_CHOICES, required=False, initial=25)
    order_by = forms.ChoiceField(label='Order by', choices=DRUG_SORT_CHOICES, required=False)

class PrescriberForm(forms.Form):
    
    prescriber_name = forms.CharField(label='Prescriber name', max_length=100, required=False)
    gender = forms.ChoiceField(choices=GENDERS, required=False)
    state = forms.ChoiceField(choices=STATES, required=False)
    specialty = forms.ChoiceField(choices=SPECIALITY, required=False)
    isopioidprescriber = forms.NullBooleanField(label="Prescribes Opioids?", required=False)
    total_prescriptions = forms.IntegerField(label="Total Prescriptions Written", required=False)
    result_size = forms.ChoiceField(label='Result rows', choices=RESULT_SET_CHOICES, required=False, initial=25)
    order_by = forms.ChoiceField(label='Sort Order', choices=PRESCRIBER_SORT_CHOICES, required=False, initial='')

class TotPrescPredForm(forms.Form):
    state = forms.ChoiceField(choices=STATES)
    gender = forms.ChoiceField(choices=GENDERS)
    isopioidprescriber = forms.NullBooleanField(label="Prescribes Opioids?")
    credential = forms.ChoiceField(choices=CREDENTIALS)
    specialty = forms.ChoiceField(choices=SPECIALITY)
    order_by = forms.ChoiceField(label='Sort Order', choices=PRESCRIBER_SORT_CHOICES, required=False, initial='')

class PredPrescOp(forms.Form):
    state = forms.ChoiceField(choices=STATES)
    gender = forms.ChoiceField(choices=GENDERS)
    totalprescriptions = forms.IntegerField()
    specialty = forms.ChoiceField(choices=SPECIALITY)

class PrescriberCrud(forms.Form):
    fname = forms.CharField(label='First Name', max_length=100, required=True)
    lname = forms.CharField(label='Last Name', max_length=100, required=True)
    gender = forms.ChoiceField(choices=GENDERS, required=True)
    state = forms.ChoiceField(choices=STATES, required=True)
    specialty = forms.ChoiceField(choices=SPECIALITY, required=True)
    isopioidprescriber = forms.NullBooleanField(label="Prescribes Opioids", required=True)
    totalprescriptions = forms.IntegerField(label="Total Prescriptions Written", required=True)

    

templates/prescriber_portal/addprescriber.html
{% extends '../shared/base.html' %}
{% load static %}
{% load widget_tweaks %}
{% block content %}
<div class="container">
  <div class="text-left">
      <h2 class="section-heading text-uppercase">Add Prescriber</h2>
  </div>
  <br>
  
  <form name="form" method="post" action="{% url 'addPrescriber' %}">
      <div class="form-grid mb-3">
          {% csrf_token %}
        <!--Prescriber First Name-->
        <label for="id_fname" class="form-label">{{form.fname.label}}:</label> 
        {{form.fname | add_class:"form-control"}}
        <!--Prescriber Last Name-->
        <label for="id_lname" class="form-label">{{form.lname.label}}:</label> 
        {{form.lname | add_class:"form-control"}}
        <!--Gender-->
        <label for="id_gender" class="form-label">{{form.gender.label}}:</label> 
        {{form.gender | add_class:"form-select"}}
        <!--State-->
        <label for="id_state" class="form-label">{{form.state.label}}:</label> 
        {{form.state | add_class:"form-select"}}
        <!--Speciality-->
        <label for="id_specialty" class="form-label">{{form.specialty.label}}:</label> 
        {{form.specialty | add_class:"form-select"}}
        <!--Prescribes opioids?-->
        <label for="id_isopioidprescriber" class="form-label">{{form.isopioidprescriber.label}}</label> 
        {{form.isopioidprescriber | add_class:"form-select"}}
        <!--Total Prescriptions-->
        <label for="id_totalprescriptions" class="form-label">{{form.totalprescriptions.label}}:</label> 
        {{form.totalprescriptions | add_class:"form-control" | attr:"type:number" | attr:"min:0" | attr:"max:10000"}}

      </div>
      <button type="submit" class="btn btn-primary mb-3">Add</button>
    </form>
</div>
{% endblock %}

templates/prescriber_portal/drug_search_results_table.html
<div class="table-responsive">
    <table class="table table-hover table-striped">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Drug Name</th>
            <th scope="col">Opioid Classification</th>
          </tr>
        </thead>
        <tbody>
            {% for drug in queryset %}
            {% if drug.rank != 0%}
            <tr>
                <th scope="row">{{forloop.counter}}</th>
                <td onclick="location.href='{% url 'details' entity='drug' id=drug.drugid %}'">{{drug.drugname}}</td>
                <td>{% if drug.isopioid == True %}Opioid{% else %}Non-opioid{% endif %}</td>
            </tr>
            {% endif %}
          {% endfor %}
        </tbody>
      </table>
</div>

templates/prescriber_portal/editprescriber.html
{% extends '../shared/base.html' %}
{% load static %}
{% load widget_tweaks %}
{% block content %}
<div class="container">
  <div class="text-left">
      <h2 class="section-heading text-uppercase">Edit Prescriber</h2>
  </div>
  <br>
  <form name="form" method="post" action="{% url 'showprescribers' %}">
    {% csrf_token %}
    <div class="form-grid mb-3">
      <!--Prescriber First Name-->
      <label for="id_fname" class="form-label">{{form.fname.label}}:</label> 
      {{form.fname | add_class:"form-control"}}
      <!--Prescriber Last Name-->
      <label for="id_lname" class="form-label">{{form.lname.label}}:</label> 
      {{form.lname | add_class:"form-control"}}
      <!--Gender-->
      <label for="id_gender" class="form-label">{{form.gender.label}}:</label> 
      {{form.gender | add_class:"form-select"}}
      <!--State-->
      <label for="id_state" class="form-label">{{form.state.label}}:</label> 
      {{form.state | add_class:"form-select"}}
      <!--Speciality-->
      <label for="id_specialty" class="form-label">{{form.specialty.label}}:</label> 
      {{form.specialty | add_class:"form-select"}}
      <!--Prescribes opioids?-->
      <label for="id_isopioidprescriber" class="form-label">{{form.isopioidprescriber.label}}</label> 
      {{form.isopioidprescriber | add_class:"form-select"}}
      <!--Total Prescriptions-->
      <label for="id_totalprescriptions" class="form-label">{{form.totalprescriptions.label}}:</label> 
      {{form.totalprescriptions | add_class:"form-control" | attr:"type:number" | attr:"min:0" | attr:"max:10000"}}

    </div> 
    <button type="submit" class="btn btn-primary mb-3">Update</button>
  </form>
</div>
{% endblock %}

templates/prescriber_portal/predict_tot_presc.html
{% extends '../shared/base.html' %}
{% load static %}
{% load widget_tweaks%}
{% block content %}
<div class="container">
    <h1 class="my-4">Predict Total Prescriptions</h1>

    {% if form %}
        <form method="POST" action="{% url 'predtotpresc' %}">
            {% csrf_token %}
            <div class="form-grid mb-3">
                <!--State-->
                <label for="id_state" class="form-label">{{form.state.label}}:</label> 
                {{form.state | add_class:"form-select"}}
                <!--Gender-->
                <label for="id_gender" class="form-label">{{form.gender.label}}:</label> 
                {{form.gender | add_class:"form-select"}}
                <!--Prescribes opioids?-->
                <label for="id_isopioidprescriber" class="form-label">{{form.isopioidprescriber.label}}</label> 
                {{form.isopioidprescriber | add_class:"form-select"}}
                <!--Credential-->
                <label for="id_credential" class="form-label">{{form.credential.label}}</label> 
                {{form.credential | add_class:"form-select"}}
                <!--Specialty-->
                <label for="id_specialty" class="form-label">{{form.specialty.label}}</label> 
                {{form.specialty | add_class:"form-select"}}
            </div>
            <button type="submit" class="btn btn-primary mb-3">Search</button>
        </form>
        
    {% endif %}
    
    <p>Predicted Total Prescriptions: <span class="label">{{predicted_totalprescriptions}}</span></p>
    
    
</div>
{% endblock %}

templates/prescriber_portal/prescriber_search_form.html
{% load widget_tweaks %}
<!--Prescriber Name-->
<label for="id_prescriber_name" class="form-label">{{form.prescriber_name.label}}:</label> 
{{form.prescriber_name | add_class:"form-control"}}
<!--Gender-->
<label for="id_gender" class="form-label">{{form.gender.label}}:</label> 
{{form.gender | add_class:"form-select"}}
<!--State-->
<label for="id_state" class="form-label">{{form.state.label}}:</label> 
{{form.state | add_class:"form-select"}}
<!--Specialty-->
<label for="specialty" class="form-label">{{form.specialty.label}}:</label> 
{{form.specialty | add_class:"form-select"}}
<!--Prescribes opioids?-->
<label for="id_isopioidprescriber" class="form-label">{{form.isopioidprescriber.label}}</label> 
{{form.isopioidprescriber | add_class:"form-select"}}
<!--Total Prescriptions-->
<label for="id_total_prescriptions" class="form-label">{{form.total_prescriptions.label}}:</label> 
{{form.total_prescriptions | add_class:"form-control" | attr:"type:number" | attr:"min:0" | attr:"max:10000"}}
<!--Result Set Size-->
<label for="id_result_size" class="form-label">{{form.result_size.label}}:</label> 
{{form.result_size | add_class:"form-select"}}
<!--Order By-->
<label for="id_order_by" class="form-label">{{form.order_by.label}}:</label> 
{{form.order_by | add_class:"form-select"}}

templates/prescriber_portal/recommend_drug.html
{% extends '../shared/base.html' %}
{% load static %}
{% block content %}
<div class="container">
    <h1 class="my-4">Drug Prediction page</h1>
    <p>Recommended Drugs: </p>
    <ul>
    {% for drug in recommended_drugs %}
    <li>
    {{forloop.counter}}: {{drug}}
    </li>
    {% endfor %}
    </ul>
</div>
{% endblock %}

templates/prescriber_portal/search.html
{% extends '../shared/base.html' %}
{% load static %}
{% load widget_tweaks %}
{% block content %}
<div class="container">
    <h1 class="my-4">{% if entity %}{{entity | capfirst}}{% endif %} Search Engine</h1>
    <h4>I want to search for:</h4>
    <!--RADIO TOGGLE: ENTITY--> <!--TODO: Consider spicing up the style on the radio buttons-->
    <div class="mb-4">
        <div class="form-check">
            <input class="form-check-input" type="radio" name="flexRadioDefault" id="flexRadioDefault1" 
            onclick="location.href='{% if entity == 'drug' %}#{% else %}{% url 'search_entity' entity='drug' %}{% endif %}'"
            {% if entity == 'drug' %}checked{% endif %}>
            <label class="form-check-label user-select-none" for="flexRadioDefault1">
            Drugs
            </label>
        </div>
        <div class="form-check">
            <input class="form-check-input" type="radio" name="flexRadioDefault" id="flexRadioDefault2" 
            onclick="location.href='{% if entity == 'prescriber' %}#{% else %}{% url 'search_entity' entity='prescriber' %}{% endif %}'"
            {% if entity == 'prescriber' or entity is None %}checked{% endif %}>
            <label class="form-check-label user-select-none" for="flexRadioDefault2">
            Prescribers
            </label>
        </div>
      </div>
      <!--END RADIO TOGGLE: ENTITY-->
      <!--FORM-->
      {% if form %}
      <form method="GET">
        <div class="form-grid mb-3">
          {% if entity == 'drug' %}
          
          <!--Drug Name-->
          <label for="id_drugname" class="form-label">{{form.drugname.label}}:</label> 
          {{form.drugname | add_class:"form-control"}}
          <!--Is opioid?-->
          <label for="id_isopioid" class="form-label">{{form.isopioid.label}}</label> 
          {{form.isopioid | add_class:"form-select"}}
          <!--Result Set Size-->
          <label for="id_result_size" class="form-label">{{form.result_size.label}}:</label> 
          {{form.result_size | add_class:"form-select"}}
          <!--Order By-->
          <label for="id_order_by" class="form-label">{{form.order_by.label}}:</label> 
          {{form.order_by | add_class:"form-select"}}

          {% elif entity == 'prescriber' %}

          <!--Prescriber Name-->
          <label for="id_prescriber_name" class="form-label">{{form.prescriber_name.label}}:</label> 
          {{form.prescriber_name | add_class:"form-control"}}
          <!--Gender-->
          <label for="id_gender" class="form-label">{{form.gender.label}}:</label> 
          {{form.gender | add_class:"form-select"}}
          <!--State-->
          <label for="id_state" class="form-label">{{form.state.label}}:</label> 
          {{form.state | add_class:"form-select"}}
          <!--Specialty-->
          <label for="specialty" class="form-label">{{form.specialty.label}}:</label> 
          {{form.specialty | add_class:"form-select"}}
          <!--Prescribes opioids?-->
          <label for="id_isopioidprescriber" class="form-label">{{form.isopioidprescriber.label}}</label> 
          {{form.isopioidprescriber | add_class:"form-select"}}
          <!--Total Prescriptions-->
          <label for="id_total_prescriptions" class="form-label">{{form.total_prescriptions.label}}:</label> 
          {{form.total_prescriptions | add_class:"form-control" | attr:"type:number" | attr:"min:0" | attr:"max:10000"}}
          <!--Result Set Size-->
          <label for="id_result_size" class="form-label">{{form.result_size.label}}:</label> 
          {{form.result_size | add_class:"form-select"}}
          <!--Order By-->
          <label for="id_order_by" class="form-label">{{form.order_by.label}}:</label> 
          {{form.order_by | add_class:"form-select"}}

          {% endif %}
        </div>
        <button type="submit" class="btn btn-primary mb-3">Search</button>
      </form>
      {% endif %}
      <!--END FORM-->
      <!--RESULTS TABLE-->
      {% if entity == 'drug' and queryset %}
        {% include './drug_search_results_table.html' %}
      {% elif entity == 'prescriber' and queryset %}
        {% include './prescriber_search_results_table.html' %}
      {% else %}
        <div class="spacer"></div>
      {% endif %}
      <!--END RESULTS TABLE-->
</div>
{% endblock %}