edu/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('about', views.about, name='about'),
    path('facts', views.facts, name='facts'),
    path('resources', views.resources, name='resources'),
    path('resources/<int:id>', views.resources, name='specific_resource'),
    path('contact', views.contact, name='contact'),
    path('community', views.community, name='community'),
    path('login', views.loginPageView, name='login'),
    path('register', views.registerPageView, name='register'),
]

prescribeless/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('edu.urls')),
    path('portal/', include('prescriber_portal.urls')),
]

edu/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models
from django.db.models.fields import TextField
from django_quill.fields import QuillField

class Author(models.Model):
    first_name = models.CharField(max_length=30, blank=True, null=True)
    last_name = models.CharField(max_length=30, blank=True, null=True)
    email = models.EmailField(max_length=254, blank=True, null=True)
    organization = models.CharField(max_length=50, blank=True, null=True)
    
    def __str__(self):
        if self.first_name and self.last_name:
            return self.first_name + ' ' + self.last_name
        elif self.first_name:
            return self.first_name
        else: 
            return self.organization


PUBLICATION_TYPE = (('Article' , 'Article'), ('Blog','Blog'), ('Local Resource', 'Local Resource'))

class Article(models.Model):

    def preview_img_path(instance, filename):
        return './prescribeless/prescribeless/static/img/preview_img/{0}.jpeg'.format(instance.id)

    title = models.CharField(max_length=255, unique=True)
    body = QuillField()
    pub_date = models.DateTimeField(auto_now_add=True, serialize=True)
    author = models.ForeignKey(Author, blank=True, null=True, on_delete=models.CASCADE)
    publication_type = models.CharField(max_length=20, choices=PUBLICATION_TYPE)
    preview_text = models.CharField(max_length=255, blank=True, null=True)
    preview_img = models.ImageField(upload_to=preview_img_path, blank=True, null=True)

    def __str__(self):
        return self.title

class Fact(models.Model):
    title = models.CharField(max_length=255, unique=True)
    body = QuillField()
    date_modified = models.DateTimeField(auto_now=True, serialize=True)
    internal_resources = models.ManyToManyField(Article, blank=True)
    external_resource_link = models.URLField(blank=True, null=True)

    def __str__(self):
        return self.title

class Quote(models.Model):
    author = models.CharField(max_length=255)
    quote = TextField()
    date_modified = models.DateTimeField(auto_now=True, serialize=True)
    internal_resources = models.ManyToManyField(Article, blank=True)
    external_resource_link = models.URLField(blank=True, null=True)

    def __str__(self):
        return self.author

edu/forms.py
from django import forms

class ContactForm(forms.Form):
    INTEREST_CHOICES = (
        ('Utah Nalaxone', 'Utah Nalaxone'),
        ('Substance Use Disorder Support Groups', 'Substance Use Disorder Support Groups'),
        ('Mental Health Support Groups', 'Mental Health Support Groups'),
        ('Emotional Wellness Activities', 'Emotional Wellness Activities'),
        ('Virtual Sponsorships', 'Virtual Sponsorships'),
    )
    your_name = forms.CharField(label='Your name', max_length=100)
    email = forms.EmailField(label='Email')
    interests = forms.MultipleChoiceField(choices=INTEREST_CHOICES, widget=forms.CheckboxSelectMultiple)
    message = forms.CharField(label='What would you like us to know?', widget=forms.Textarea)

edu/views.py
from django.shortcuts import render
from . import models
from . import forms

ctx = { 
    'view' : 'Standard'
}

# Create your views here.
def index(request):
    ctx['facts'] = models.Fact.objects.all()[:6]
    ctx['article1'] = models.Article.objects.get(id=5)
    ctx['article2'] = models.Article.objects.get(id=3)
    ctx['quotes'] = models.Quote.objects.all()[:3]
    return render(request, 'edu/index.html', ctx)

def about(request):
    return render(request, 'edu/about.html', ctx)

def facts(request):
    facts = models.Fact.objects.all()
    for fact in facts:
        if fact.internal_resources:
            fact.associated_articles = fact.internal_resources.all()
    ctx['facts'] = facts
    return render(request, 'edu/facts.html', ctx)

def resources(request, id=None):
    articles = models.Article.objects.all()
    if id:
        article = articles.get(id=id)
        ctx['article'] = article
        return render(request, 'edu/article.html', ctx)
    else:
        ctx['articles'] = articles
        return render(request, 'edu/resources.html', ctx)

def contact(request):
    ctx['form'] = forms.ContactForm()
    return render(request, 'edu/contact.html', ctx)

def community(request):
    return render(request, 'edu/community.html', ctx)
    
def loginPageView(request):
    if request.method == 'POST':
        form = forms.LoginForm(request.POST)
        if form.is_valid():
            pass
    return render(request, 'shared/login.html', ctx)

def registerPageView(request):
    if request.method == 'POST':
        form = forms.RegisterForm(request.POST)
        if form.is_valid():
            pass
    return render(request, 'shared/register.html', ctx)

templates/edu/article.html
{% extends '../shared/base.html' %}
{% block content %}
<div class="container article my-4">
    <h1>{{article.title}}</h1>
    <h5>{{article.pub_date|date}} by {{article.author}}</h5>
    {{article.body.quill.html | safe}}
</div>
{% endblock content %}

templates/edu/contact.html
{% extends '../shared/base.html' %}
{% load widget_tweaks %}
{% block content %}
<div class="container mb-3">
    <h1 class="my-4">Let's Get in Touch.</h1>
    <form method="POST">
    {% csrf_token %}
    <!--Contact Name-->
    <div class="form-grid mb-3">
        <label for="id_your_name" class="form-label">{{form.your_name.label}}:</label> 
        {{form.your_name | add_class:"form-control"}}
        <!--Contact Email-->
        <label for="id_email" class="form-label">{{form.email.label}}:</label> 
        {{form.email | add_class:"form-control"}}
        <!--Contact Interests-->
        <label for="id_interests" class="form-label mb-0">{{form.interests.label}}:</label> 
        {% for interest in form.interests %}
            <span class="right">{{interest}}</span>
        {% endfor %}
        <!--Contact Comments-->
        <label for="id_message" class="form-label">{{form.message.label}}:</label> 
        {{form.message | add_class:"form-control"}}
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>
{% endblock content %}

templates/edu/facts.html
{% extends '../shared/base.html' %}
{% load static %}
{% block content %}
    <div class="container">
        <h1 class="my-4">Quick Facts</h1>
        <div class="accordion mb-4">
            {% for fact in facts %}
            <div class="accordion-item">
              <h2 class="accordion-header" id="panelsStayOpen-heading{{fact.id}}">
                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapse{{fact.id}}" aria-expanded="true" aria-controls="panelsStayOpen-collapse{{fact.id}}">
                  {{fact.title}}
                </button>
              </h2>
              <div id="panelsStayOpen-collapse{{fact.id}}" class="accordion-collapse collapse" aria-labelledby="panelsStayOpen-heading{{fact.id}}">
                <div class="accordion-body">
                  {{fact.body.quill.html | safe}}
                  <div class="flex">
                      {% if fact.external_resource_link %}
                      <button class="btn btn-sm btn-light mb-1" onClick="location.href='{{fact.external_resource_link}}'">
                        <span class="link">Read More</span>
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="primary" class=" link bi bi-arrow-up-right-square" viewBox="0 0 16 16">
                            <path fill-rule="evenodd" d="M15 2a1 1 0 0 0-1-1H2a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V2zM0 2a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V2zm5.854 8.803a.5.5 0 1 1-.708-.707L9.243 6H6.475a.5.5 0 1 1 0-1h3.975a.5.5 0 0 1 .5.5v3.975a.5.5 0 1 1-1 0V6.707l-4.096 4.096z"/>
                          </svg>
                        </button>
                      {% endif %}
                      {% if fact.associated_articles %}
                      {% for resource in fact.associated_articles %}
                      <button class="btn btn-sm btn-light mb-1">
                        <a href="{% url 'specific_resource' id=resource.id %}">
                            {{resource}}
                        </a>
                      </button>
                      {% endfor %}
                      {% endif %}
                  </div>
                </div>
              </div>
            </div>
            {% endfor %}
          <div class="py-4">
            <!--Opioid deaths by state map-->
            <h3 class="py-3">Opioid Overdose Deaths By State</h3>
            <div class='tableauPlaceholder' id='viz1638851195819' style='position: relative'><noscript><a href='#'><img alt=' ' src='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;In&#47;Intex2_16388509893170&#47;DeathState&#47;1_rss.png' style='border: none' /></a></noscript><object class='tableauViz'  style='display:none;'><param name='host_url' value='https%3A%2F%2Fpublic.tableau.com%2F' /> <param name='embed_code_version' value='3' /> <param name='site_root' value='' /><param name='name' value='Intex2_16388509893170&#47;DeathState' /><param name='tabs' value='yes' /><param name='toolbar' value='yes' /><param name='static_image' value='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;In&#47;Intex2_16388509893170&#47;DeathState&#47;1.png' /> <param name='animate_transition' value='yes' /><param name='display_static_image' value='yes' /><param name='display_spinner' value='yes' /><param name='display_overlay' value='yes' /><param name='display_count' value='yes' /><param name='language' value='en-US' /></object></div>                <script type='text/javascript'>                    var divElement = document.getElementById('viz1638851195819');                    var vizElement = divElement.getElementsByTagName('object')[0];                    vizElement.style.width='80%';vizElement.style.height=(divElement.offsetWidth*0.75)+'px';                    var scriptElement = document.createElement('script');                    scriptElement.src = 'https://public.tableau.com/javascripts/api/viz_v1.js';                    vizElement.parentNode.insertBefore(scriptElement, vizElement);                </script>
          </div>
    </div>
{% endblock %}

templates/edu/index.html
{% extends '../shared/base.html' %}
{% load static %}
{% block content %}
<div class="hero">
    <img class="hero-img" src="{% static 'img/hero-1920.jpeg' %}" alt="">
    <div class="hero-caption">
        <h1>Mental Health Matters.</h1> <!--todo: consider making this db updatable.-->
        <button class="btn-primary btn mt-3"><a class="text-white nav-link py-0 px-3" href="{% url 'facts' %}">Learn More</a></button>
    </div>
</div>
<div class="container">
    <!--Quick facts snapshot-->
    <h2 class="m-4">Get the facts:</h2>
    <div class="card-container m-4">
        {% for fact in facts %}
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">{{fact.title}}</h5>
                    <p class="card-text">{{fact.body.quill.html | safe |truncatechars_html:150 }}</p>
                    <button class="btn btn-outline-primary">Keep Reading</button>
                </div>
            </div>
        {% endfor %}
    </div>
    <!--Article Section-->
    <h2 class="m-4">Read the latest research:</h2>
    <hr class="featurette-divider my-4">
    <div class="row featurette m-4 py-4">
        <div class="col-md-7">
          <h4 class="featurette-heading">{{article1.title}}</h4>
              <p class="lead">{% if article1.preview_text %}{{article1.preview_text}}{% else %}{{article1.body.quill.html | safe |truncatechars_html:150}}{% endif %}</p>
          </p>
          <p><a class="btn btn-secondary" href="#">Read on »</a></p>
        </div>
        <div class="col-md-5">
          <img class='img-fluid' src="{% get_static_prefix %}img/preview_img/{% if article1.id < 7 %}{{article1.id}}{% else %}2{% endif %}.jpeg"alt="">
        </div>
      </div>
      <hr class="featurette-divider my-4">
      <div class="row featurette m-4 py-4">
        <div class="col-md-5">
          <img class='img-fluid' src="{% get_static_prefix %}img/preview_img/{% if article2.id < 7 %}{{article2.id}}{% else %}4{% endif %}.jpeg"alt="">
        </div>
        <div class="col-md-7">
          <h4 class="featurette-heading">{{article2.title}}</h4>
              <p class="lead">{% if article2.preview_text %}{{article2.preview_text }}{% else %}{{article2.body.quill.html | safe |truncatechars_html:150}}{% endif %}</p>
          </p>
          <p><a class="btn btn-secondary" href="#">Read on »</a></p>
        </div>
      </div>
      <hr class="featurette-divider my-4">
      <!--Testimonials-->
      <h2 class="m-4">What people are saying:</h2>
        <hr class="featurette-divider my-4">
        {% for quote in quotes %}
        <div class="m-4">
            <figure>
            <blockquote class="blockquote">
              <p>{{quote.quote}}</p>
            </blockquote>
            <figcaption class="blockquote-footer">
              {{quote.author}}
            </figcaption>
          </figure>
        </div>
        
        {% endfor %}
        <hr class="featurette-divider my-4">
    
</div>
{% endblock %}

templates/edu/resources.html
{% extends '../shared/base.html' %}
{% load tz %}
{% load static %}
{% block content %}
<div class="container">
  <h1 class="my-4">Resources</h1>
  <!--Card previews of all resources-->
  <div class="row mb-2">
  {% for article in articles %}
      <div class="col-md-6">
        <div class="card row g-0 border rounded overflow-hidden flex-md-row mb-4 h-md-250 position-relative">
          <div class="col p-4 d-flex flex-column position-static">
            <strong class="label d-inline-block mb-2 text-primary">{{article.publication_type}}</strong>
            <h3 class="mb-0 publication">{{article.title}}</h3>
            {% localtime on %}
            <div class="mb-1 text-muted">{{article.pub_date}}</div>
            {% endlocaltime %}
            {% if article.preview_text is not None %}
              <p class="card-text mb-auto ">{{article.preview_text}}</p>
            {% else %} <!--Failsafe author description generator for when an article doesn't have preview text-->
              <p class="card-text mb-auto ">Get the latest on mental health trends and tips from {% cycle 'syndicated columnist' 'trusted author' 'vernable reporter' %}: {{article.author}}</p>
          {% endif %}
            <a href="{% url 'specific_resource' id=article.id %}" class="stretched-link">Continue reading</a>
          </div>
          <div class="col-auto d-lg-block">
            <img class="preview-img" focusable="false" src="{% get_static_prefix %}img/preview_img/{{article.id}}.jpeg"/>
          </div>
        </div>
      </div>
  {% endfor %} 
  </div>
</div>
{% endblock content %}